"""세대 전달 함수: the estimator has to recover a handover we planted, and has to *not* invent one."""

import math
import random

from trend_engine import kernel as K

PLANTED = [0.0, 0.05, 0.15, 0.30, 0.25, 0.10, 0.05] + [0.0] * 6  # peak at 3 weeks


def wave(n: int, centre: float, width: float) -> list[float]:
    return [math.exp(-((i - centre) / width) ** 2) for i in range(n)]


def make_pairs(count: int = 12, n: int = 90, noise: float = 0.02, seed: int = 3):
    rng = random.Random(seed)
    pairs = []
    for _ in range(count):
        young = [max(0.0, v + rng.gauss(0, noise)) for v in wave(n, rng.randint(25, 60), rng.uniform(3, 7))]
        old = [max(0.0, sum(PLANTED[k] * young[t - k] for k in range(len(PLANTED)) if t - k >= 0)
                   + 0.05 + rng.gauss(0, noise)) for t in range(n)]
        pairs.append((K.normalise(young), K.normalise(old)))
    return pairs


def test_recovers_the_handover_it_was_given():
    k = K.fit(make_pairs())
    assert k is not None
    assert k.peak_lag == 3  # planted at 3 weeks
    assert 2.5 <= k.mean_lag <= 4.5
    assert 0.7 <= k.gain <= 1.3
    assert all(v >= 0 for v in k.h)  # a handover cannot subtract attention


def test_a_shared_shock_lands_on_lag_zero_instead_of_inventing_a_delay():
    """Both ages reacting to the same news is not diffusion, and must not read as diffusion."""
    pairs = [(y, [min(1.0, v * 0.8 + 0.05) for v in y]) for y, _ in make_pairs()]
    k = K.fit(pairs)
    assert k is not None and k.peak_lag == 0
    assert k.instant_share > 0.5


def test_no_fit_from_too_little_data():
    assert K.fit([(K.normalise(wave(20, 10, 3)), K.normalise(wave(20, 12, 3)))]) is None


def test_forecast_evaluation_reports_both_baselines():
    pairs = make_pairs(count=16)
    ev = K.evaluate_forecast(pairs[:10], pairs[10:], horizon=8)
    assert ev and ev["horizon"] == 8 and ev["n"] >= 8
    assert set(ev["mae"]) == {"kernel", "lag", "flat"}
    assert ev["beats_lag"] > 0 and ev["beats_flat"] > 0
    # on data that really was generated by a kernel, the kernel should win
    assert ev["beats_flat"] > 1.0


def test_kernel_summary_shape_is_stable_for_the_dashboard():
    k = K.fit(make_pairs())
    d = k.to_dict()
    assert set(d) == {"h", "gain", "peak_lag", "mean_lag", "spread", "instant_share", "rows", "keywords"}
    assert len(d["h"]) == K.K_MAX + 1 and d["keywords"] == 12
